### ISSUE TITLE
Add a new scheme to vidyut-lipi

### ISSUE THREAD

**Issue by akprasad** [ambuda-org/vidyut#107]
My soft goal is 50 supported schemes with good quality. We currently support 32, which means we have 18 more to go.

How to create a new scheme:

1. Find a scheme in https://github.com/indic-transliteration/common_maps/ that is not supported in vidyut-lipi. You can find a list of our supported schemes in `enum Scheme` under `scheme.rs`.

2. Generate a basic mapping for your scheme by updating the `ALLOWED` list in `create_schemes.py` then running `./scripts/create_schemes.py`. If this command succeeded, you should see data for your scheme in `autogen_schemes.rs`.

3. Add a new value to `enum Scheme` for your scheme, then run `cargo check` to see which parts of the code you need to update. Proceed to step (4) once `cargo test` passes.

4. Add test cases for your scheme to `basic.rs`. At minimum, update the following:

    - `sanskrit_independent_vowels`
    - `sanskrit_dependent_vowels`
    - `sanskrit_ayogavahas_etc`
    - `sanskrit_consonants_non_vedic`
    - `sanskrit_symbols`
    - `sanskrit_basic_sentences`
    
    In general, assume that whatever [Aksharamukha](https://aksharamukha.appspot.com/converter) produces is correct.
  
    If your scheme is lossless -- that is, if we can convert Devanagari to your scheme and back and get the same information -- then update the `assert_two_way_pairwise` call. Otherwise, try using `assert_one_way_pairwise` instead.

5. If your scheme has its own quirks or conventions, add tests for these as well. For examples, see `thai_preceding_vowels`, `tibetan_subjoined_consonants`, or `khmer_sign_robat`.

6. Compare your output to an existing transliterator like Aksharamukha. You can run `make debugger` to build and run our debugger. To make your scheme appear in the debugger, you will need to add your scheme's name to `schemes` and `schemeNames` in `vidyut-lipi-app.js`.

7. Once your scheme passes tests and looks good in the debugger, create a PR so we can merge it in.

**Comment by ankit-pn** [comment]
hey i would love to work on it. it would be great if you assign this to me! thanks
