### ISSUE TITLE
चंचूर्यते and पंफुल्यते

### ISSUE THREAD

**Issue by akprasad** [ambuda-org/vidyut#148]
@neeleshb while working on #145 I noticed a TODO in one of my tests.

```
// TODO: sk also has caMcUryate, paMPUlyate -- why?
let car = d("cara~", Bhvadi);
assert_has_ta(&[], &yan(&car), Lat, &["caYcUryate"]);
```

Why does SK also have चंचूर्यते and पंफुल्यते ? What rule do these come from? https://ashtadhyayi.com/sutraani/sk2637

**Comment by neeleshb** [comment]
In the state of "च + चर् + य + ते" -
1) चरफलोश्च 7.4.87 gives नुगागम on the अभ्यास
2) उत् परस्यातः 7.4.88 gives उत्व on the अकार after अभ्यास.  
Together we get चन् चुर् य ते । Then हलि च gives दीर्घ, giving चञ्चूर्यते ।

**Comment by neeleshb** [comment]
Oh sorry I completely missed that. See vartika under 7.4.87 "स च पदान्तवद्वाच्यः" - The नुक् आगम behaves as it it is पदान्त. That is for allowing optional परसवर्ण by वा पदान्तस्य, giving चंचूर्यते ।
