### ISSUE TITLE
prakriya: add search box for dhatus

### ISSUE THREAD

**Issue by akprasad** [ambuda-org/vidyut#21]
Similar to sites like ashtadhyayi.com. A list of 2000 dhatus is too much to reasonably scroll through, especially since they are in their aupadeshika forms.

**Comment by akprasad** [comment]
Not sure when I can get to this, so I'm unassigning myself for now.

**Comment by akprasad** [comment]
Added a primitive box to search by number. Marking this as done for now, but we should improve it.

**Comment by shreevatsa** [comment]
Nice!

As for improvements: yeah ideally should also be searchable by the dhātu itself.

(Also it's confusing that the numbers are rendered in Devanagari but we don't search with Devanagari numerals: maybe the digits shouldn't be transliterated into Devanagari in the first place?)

**Comment by akprasad** [comment]
The placeholder text is misleading, but both roman and devanagari numerals should work. Ihave a WIP PR that allows search on the aupadeshika dhatu and meaning (I.e. we can search वदिँ but not वन्द् -- not great, but still an improvement!) and I'll fix the text there.
