### ISSUE TITLE
prakriya: Nice urls for easy sharing

### ISSUE THREAD

**Issue by shreevatsa** [ambuda-org/vidyut#23]
May be nice to encode state in the URL ([general motivation](https://betterprogramming.pub/how-and-why-you-should-store-react-ui-state-in-the-url-f2013a204cb2), [how to do it with Alpine.js](https://codewithhugo.com/alpinejs-x-data-watch-url/ )), for easily sharing a specific prakriya or dhātu view with others.

**Comment by akprasad** [comment]
Added partial support (encodes the active tab and the active dhatu). Will add more over time.
