### ISSUE TITLE
prakriya: side-by-side view for different forms for the same inputs

### ISSUE THREAD

**Issue by shreevatsa** [ambuda-org/vidyut#24]
When multiple forms are generated (e.g. "भवतात् , भवताद् , भवतु"), may be nice to see all their prakriya-s side by side. (Basically make the entire table cell a link/action target, rather than an individual generated form inside a table cell.)

(nice to have but a little trickier on the frontend side)

(Above quoted from https://github.com/ambuda-org/vidyut/pull/19 — may fit well with https://github.com/ambuda-org/vidyut/issues/23 if all the inputs (lakāra, puruṣa, vacana…) are the "state".)

**Comment by akprasad** [comment]
Closing as out of scope for our demo. I also think this might be tougher given that we're also displaying sutras -- there's less screen real estate to play around with.
