### ISSUE TITLE
Cargo not found when running in MSYS2

### ISSUE THREAD

**Issue by VedantMadane** [ambuda-org/vidyut#3]
![image](https://user-images.githubusercontent.com/6527493/203777847-075340c1-604e-4de6-abf8-d17b726f9f62.png)

make not found when running in windows

**Comment by akprasad** [comment]
Thanks for filing this issue. `cargo` is the Rust package manager and must be installed first:

https://doc.rust-lang.org/cargo/getting-started/installation.html

Let me know if issues persist after following the instructions above.
