### ISSUE TITLE
prakriya: Clicking on a dhātu should scroll to top

### ISSUE THREAD

**Issue by shreevatsa** [ambuda-org/vidyut#30]
To reproduce:

1. Go to https://ambuda-org.github.io/vidyullekha/
2. Scroll a couple of pages and click on a dhātu
3. The resulting page will be scrolled to the bottom (the Lrn forms etc), instead of being at the top (Lat).

(I guess it's just retaining scroll position and rendering new contents, but it's a bit confusing every time.)

**Comment by akprasad** [comment]
Thanks, fixed this and a few others in #31.

**Comment by shreevatsa** [comment]
I think there's a similar issue again with the kṛdanta-s now, e.g. if you go to https://ambuda-org.github.io/vidyullekha/?tab=krt&dhatu=01.0001, click on (ल्युट्) भवन, scroll down to the bottom of the page and click on (ण्वुल्) भावक, then things change at the top of the page with no indication that anything has changed.

**Comment by akprasad** [comment]
Fixed in `fb86ee55`.
