### ISSUE TITLE
wrong closing tags in vidyut-prakriya's `index.html`

### ISSUE THREAD

**Issue by vipranarayan14** [ambuda-org/vidyut#38]
There are wrong closing tags in the following lines of the [vidyut-prakriya's `index.html`](https://github.com/ambuda-org/vidyut/blob/7dd2114f11892f035533bda70f2a2dbff5917fa5/vidyut-prakriya/www/templates/index.html):

- [L213](https://github.com/ambuda-org/vidyut/blob/7dd2114f11892f035533bda70f2a2dbff5917fa5/vidyut-prakriya/www/templates/index.html#L213): should be `</a>` instead of  `</div>` 
- [L231](https://github.com/ambuda-org/vidyut/blob/7dd2114f11892f035533bda70f2a2dbff5917fa5/vidyut-prakriya/www/templates/index.html#L231): should be `<input ... />` instead of `<input>...</input>` since input is a self-closing tag.
- [L244](https://github.com/ambuda-org/vidyut/blob/7dd2114f11892f035533bda70f2a2dbff5917fa5/vidyut-prakriya/www/templates/index.html#L244): should be `</div>` instead of `</ol>`

See the lint errors on [Prettier playground online](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAiHMoLNnC4ATMeXKoacGF3JhKXAE4BnZYJABXGADMAtAA4hAejkKlK8lC5L9ANwCWcAO4AHCJpghNWh4WH0vd2kYSn5pOA8wOFMIqMoAGnJ3KHcYdy46U20wfLh+AEYAOgAGa1tUOiyAa3JNODp9d0hxECpW431pLhUkNNqMU1NyAEFXCEjyYy4E6Ba4AEcDOG0YbSQqGBgfXasrba4wRohXOE1jOggvCsgaKy4rAGZzAE4ygHZzAHkCZ1XIwOhwBgANUiAE8DHRwY0NKgrKDwXUipp3D4YORtJowPpqIdjlYwNIoBUVO46BEoNIwNptE8IDRRCjMdiYBiwFiceQ4sYbniCUSDkckCdyZSAFbaOINVyaCpQZRWKA+F4AASy0k6phgmh42ga8CNuWgp2NvK5WsqACYKr8rVBOTiKjQshU5ezTjacTy+biYDCfKUhDQINJ4XAgvjCdYzrkwK8fD5vdpfW7uSx5KhswK4ELNCKEyBiRKTgYNY1eCyXvkfFk4HKte8KgAPTtWPXbMkUj1en0gBgc-05qB57Yw8HkENh-TwDswMlM0S5+TkCpcUzVuKaBqq8iqYAbzebpcwUxxSDm9zQPZ7m6HuAAbjP5AAvhuOSH0RIrEoKRZBYFhgAAUjxZRyB8TQIBlOAwBgAB9Q9mn4cghArUleBySgDAAI3rV4aAIgxBlMfxeCsDxpDhFdDTgOArBoLgsho2EjFMWCuEaLEYS4IJwO-KAIKg3FeEoZD3CZTZtHIDCsPFHC8MI4jnDIiiqI4uijCsGTtDkoSRLAyDWN5CA52kAAKJwlAASnIYSJBgaQ1G4Jl9B8UwynXScFHgGgfG4eByA7UxjH8fRrJ8GQuAydxHKychgGARxnDgL9vxHD981iqBbHPPKeDCwpKAeDpyHQfgMJqEcMg5fLR0E-zz3PSg+n0ABiIQPza9yuE8rCrhuJAnwPZteta-ryC1MAGguCpYPiBAYH0XQYCmJD3GuYg4piuL7KmmbN3Cy8BniLgDsGKk4GXI6QD6trCoUV5R1OJqf1ROAgpCiEANcsQxIQaRzLgpyTPEUSzPOcGVAI7RrMc5zWHhAahpAO47vIGgYVMAAWPy81UebBu0Ly8ftHHNAJoIOqLbqgiQUmMfh6yAHJcigdmHtm+bOkaJbWmuMIhA2-AuAIjmuZ50RUvITn3AAcR4TbsnZgAfNzP0-FEuDqEmPPJoQfEp6naZ6en+iEHqemZo3F0ljm+JgWWejmhbBeWkW1rF5QJal9mXbdhh5aDgAlQZYCmdWtayvXbGALqFENsmKdMKmaBpwnLc6m2mZZ42QDZ9nDJ8N2+c9oWVtFkBxad0uDHLh7Q7SxuCNVmP3E17Xdbe8gupE4n0aL02M-NnPegZ-O7cLx3A8liAjArj2Bern31v9hvF+XlupgIpeYATgD4SByCQbByyUdA6GcdhyyeL49wBOQ+HwSRiGXMl2c56EA-NH3DjLIyRTAdjoETBQxQcT3knL-TGIRTAHzoG5S8GcwFzjulecExhcSkQzkEM6mCLquCuo-fiXBbr3V9FAi0BUfzRGAiPfQkVYCIIgMgjBy5TDYNxP-fciCIF5kNC9IRlAmEmzNj4cKOdW4K20AAVUNM4Hu8dUSUBEQFMRcCx5UykRbd60QNGoGiOIkAOiYLSNEOHLY8Ij5qJeiiYRX0GEyBBAfOiDjArBSGJlcKkVNDrXgD4TIk4yHPwoZQGSMB-AwkEZuYxmgNFCLctoyRlicrTX6qgVOrNMGILoJsUwABWKoVRyDjRfMdE6bVCHLmIVdbYcB0yaBjPZCorRvGJCmAiDmgATSHZhkdmFQ3ZPROioTQvA9BCGQgRbgUBGhVOqZuJAVt9Ds2wpKV42hqAyEoAJGE7hiKGSUTwdwVh2bkAANR4iCe0mMvp9ajNeoDJ5xiUkOwkePPRk9am+xAFwLwbFcTHKNPgTB1lGnNNab6F5mT4muVMeY75BCDREKEHEEhAA5CAABlEhRoIW3NaIZOgMAW6OJAnCxxiTcrfV+j4zxNKqWAwpUYllqJKVZIRb8+pMUjRPwEpQslQRUlfOkQsBBSDpAws5fE1ETK8yoncTCMQjjv7-Vvhfe+n8oamTvhZAUGgYAGFflkVWg0P4o2MT9bxoVwruGtv87a1xMBGoMH5VAepXB1DIgcFYcCCK8EKH9UwAA2UpnCrxeEiaFOCT43LeSpuVa4mgkCBuDT4iwpSgirwuPoeaUhNBbVyC6t1cSABkuQlDaFfAobQ+VSrnXRZdbFeKtBXXOCWuArqhgGAqE3GQWwNDko+jwOoVhfXRLof5a19K7WmAdfoTtO04B7UGHE1Ak7-UfJAOmk0mbw1lNQdGnImU430jgAm8eybRp7pDeYbN7t+Z5qEAWrQxaV1rsEhk-qlb3DVtrcVScPLm0kOssu3acUhUjvrWO2lW7p2Kq8X9OoQFB0ljgagxIsAbgbsoGUUxLCrxSsjaYd4YCUVNpABirgrb8Ududd2t1-bYpxG2VwEd+GHHBJA9Ry64HGM9uNduAIw7fQ+HHWh-cYh6E2r+qVRdJt+XkI3V6jR8swkvzfnAD+OtaVqecXJhlN88xetKtsiqQh0AQdXXFVTO0jHcAIm0WR7MeIwggLwLgAAJFROsUROZc09fMbREK4nCpGBUXkjQea8yKndibyDppPbGpeF63J8Nwz+maqAIDQJWEgEhBTwwgGIDFzzFCADSWhxnuEo2ivjYGg41a0N3EdeXaFJIUB1mB5BCv5E2PoMrXBYtVa0KxbI9W6mgaus1zQrFw5td9D16ARjTihaQjJqlgXGBh20DwKYeo-N9x20Y3Q4IkKlUi20daPAZB1Z6No8eyWY1nrS3EDL-h9xxKKitycRXBu9RHLZaAcB7Ioj+113L+XJz9eK-oHFd29QVER90RtDWaMc321AJwOGQ4Q5h1Dv7fWAcldR-diomLOhTb+Zj9mi2ZSqzgPjqwkPXnE7h4DkA5PkeEB4DT3l7MBKYqZyztnVL1sXYnEVHsDmTPwqM-O-x+huAhLUK0Hx+AzWwAtS3YLuhtqrdefh9H02QDcCpDkcEvouPy65Yr3xC7HUW72kabQrEHtdaEeq0xXgIrwjoDjPG+NSM8LnOqiK7gOyXtI+gzLmgfs5acXCpZ8tXLWSEC79t7u2IAG0qgAF0hCOT0yn6paebKZ4oa7waHvc9lCLyAEvQ8lltQrxn831fs91-tI35vTyZfJ9bwFBVw-Nzt6rxUGvOf3C5-eH3rKA+ZoT871P7vef8YL9L2P8faV0+T+n3XopW+W9LOpV7+Fo+d8r6z27uvoaT9L-6jfrvd+8+-Ef2Xk6L+19v9n+YT-Yfc-JfNVWZDVE6RxB3LbCA5DHxBTZ3ChKYWgHgWMbLGAn3OBP3YwAPIPAmUPIsYMCPYwKPGPVBOPL7LLC-IRK-MfH-JAibOAfPQAnfFKPfSvVfeglA+vZg6-NgjvC3Tg1UXPXvYvRfL-OVIfVvBJKgtvPgyfQQxg+fUQ7fFgug5AoQzfZQ0-WguQjg9Qxg4-LQp-Z5GgmA0w1vNQhg3PB-Iw8Q5-XQgQ-Q3PD-Wwlg1gqyfgxApwgA1wqQ+VC-UA-8MvSAudcAtqDkMLGBBxOlW1MIlEAzKGeIuXVgGIlDPVLVA1a+KGMSS+Q1XtZCPiKOFQRGZGESWdWI+ApdQTMtDJT1ZIvMBDUxO9A9CNY9V7Fod7GPRLG9VNZo+ALNOqSuAWfNcEd9ao3tCtKtLYQDWDYDVFM3GjOjdtATLtITPtAdNjMTEcRqODGdCdIwKdEEB3SooQGzL9DdRogNINfdfow9UjFLN7eNGCa9EaXo64+9R9IYl9cAUYotRjc4tAzcP9ADOtBtXjTHM4qDS8GDT6aaFEBDcdWA+AaAhQKTYUTDPJbDM0PDAjOBIjNhDhVBcjcBHocEltXFejFYldNYljQddjTjMobjU3WnfjGzGkmrLY96CTL6NEplWTUIk4sxZTcJezb1J6DTYUrTdVXTbQpIsUvYpEsI-kiovxKKIQF2fAUMTKZKXkKQeASrABc1EojdbTX3f3BEXAkPVBMPbTSPaPFBPJcggBSg4LFxWVLlDDHdPopIe0R9GQ4xLRBLfBUk+YlkprRoHBbic0fZLgFnQxYwgMxFYM5kwXCMoo2MkdeM4I-w4LNRYCNlZVKHRU0qZXdUtXDUrUxPIqQ0UxGuNNd4zNEpKs8IkxJ7e0AXGbayQWNEMHGFdRBMhFNs5s+3AU1UgJE2OKcspaOKTMQEoA1QVZGeYwmaANe4C4KgV4saC9CaVURZNwsksDVjChS8cgDWDWBWUwEZOwk6XNL2YWVaTeTaf4-aI8kdBInfEI2I-0jlAInM7MxUtbGAQs2lbTREqAgCBIz8tIzVekXIrIm+HI7VaQN1VCKJS1MoszcKCzLwfQazcY41PyH8LIHwIwOcLUxcTBFFa7dodFN1AAMRpGxMex3SwJwPj2eII1xmDI-E6TgHKmQRuH0E1LDHIA2BuBhHIGskAFpIQAIUgMgCJKB5EMhlAwAKgR1iKjAUTctGBcpiyxyBg1diDSUbhL01jjS5yFAGhTEuLfILLh5FyQBbYvi7ya4-kNoP1S1e1rJpAWQ4heZVyIB1yej6yM1+iSkOLQ9eBhzQSSorjQqkgyhWi8kbikhfgI1z0PsOKOzGsrofLIA-L2kmluAukel2Z+lBlhkYTdiz9ZjTFUFWhpBTA0rBiDzaMKTlifKNih0OMsxYSaqG0MSuEUqw1PjWrvKRNogertjR1EMcs3pcyGhoiAKvp2FVVWcdKYLQZtV4LWBgLWAatOhZxwpBgVAl00wIFJB0NEU8YygqZvSfIkquEsSXS4STdBqrx8Z0F8SSM8F2yRww5aI4QEQ4AkQphjsURbc4Tgl3r4qBi4lrIphCxIxyAIBjAU5TEKlJpc5p4QAJT4IwtUL5lF8ehxlJk-kZk5kFkRxAauJNMuAE4Kg+piBRjdAFgaRMoyJeB5JskMbtzKlsbHV5ZJJpJZIthibw8JkpkQAKaeAqaGAgJWgGajo4SrBuS9jeStKzM4FWJwo-diScZwouAjBLIuLLBAS09JYSixD5BcoDdaFzNyocLTjGMA4FIaoFYZZTzzybNXaaoMIg4Ah2ZE86jXAHbLMnUu1fb3bFZuZmz5ZkL8iuYjSZTcz3zwjMKypw6fbJY3b-bg4460oE7jUCjDSdcraVCZcEjxTC6UKGhtgU6qUeNM6nbqM3VmRwQ+ATE-byA6oGAAAZCAe7PgcgctICBEbEV8FENWmXO2qIu3OtSIlYLCx2qoyOnO7uxucuYOiTXAVkLIXgPECAaACoKe6I2eo3KGc8MSDaYIHXS7RScsZSTZDSciChbSHeFcLoFQJCYyD8a+6CD3Q8XgVC7YBSTCR+kkTZXgONI4CoXgI+3gcEYiaiF+iiHgKANLRIX+uE8+uY7C1eldKO-2j+oOiykOxFOCVmncTG3cuyhQaGndPBGRfASJeSGSY8ScaAF8JGyyVG9GuBHIfIanAW-QPGhCJCQm5oPTamziK8OmhOUYMvVQPabIbIEqLwL7cgSZVUc0fwdXPUmPfxOcICdGhyjZE4VBt+iZUQKYUiV+hOGCOCcRmAE+1WlErJBhtOCMAifRZmqQVmjB0KSa4MVhvEU9TIbm7YOCPgBgIxuISMV0JRWhJ5EizQPwXQeSLhmEX8aJ3gBgPYLwTKDQa4RwCAXEPwOuoCNyHIHGAwdQDIHgap3BdwSSXEXsLgNMQtFGhPMvAiDXZoIYDhiSqYiocgAAdSKaWEymkFBxRoMBLGc1AeiXIEaCYmCSXhLG0ZuCGH8FLjmcOCMCeUiUklEoMCEZDHktIprkPoyAmwkr4YYXIA0YAUyZLDpvkgVsygiARCOambxFYgtJuDgh0FcbVteU8YxiYdEHwEskCYdQkoMEybRp4Akuebcj0bpvICBf8G0AyGCn8cymyWMIcqFqkgMjkmJoYF1LgJKnJbgAcZWA2ccfxqQj2aVhyG80IieQAElRb5JYpJlRnMA5hh7tBLJvnA9WgNh3BWhjwFhWhMp2WYBOWCJjwwBIBqwXHyA6K9GtmjRwEy9nglBYBcWYIWbCWFy85ca0ov7O1KXbXLtEWGXJxHnbHNIWoToHXymuBBXT756ioJMGKnAEQYQMgPMDA1ASpIoEQHhjx7hh6IgTEmXnnmgCIJKeaSW0pAH96QHcRpGutDIEYbQCJ965xeH5mFB3AGBLHTB0HMH6X9IGBHBvATRlAzQGbxnMp0nAgy8m4Tqxa41JI6B7moBEg5WEmTEP65m3mnGwsOH0W+ARWD6U3QW1s07FVcHx0q6UiDqC01q9qAJ2ANqQA0gQA-ttBkBQAtA4IvBXcEAL2UB8hAUYQL3T2+nzhVmYBEclA+7mxkBFg6BdA32jQLhlAcVYowB97kBDRNhT2fpnNpAPs+6eBeAznJkdX5shguZeBkB-ljaT3H76AxnXtYNEgcV72cgdocgYRcPGRX2QAshdAAhhteBWJ-38ggOQA5QOwcV97wQABFAwMpuAdjwDuAU92KHQG4XDo9gj2CLIGAMZyIaIZAB9CTyhuAMZo0HwXD5aJj64AjjYYTsrPLB9-5bQUwVUS9S9AjqVgwGV1dI0VjrgUTzj3QT0aDlpcTuuPjuAJAw0dwX1VdG4X91UVz7z7QXzwT4T8L09+GJT1IZAe0OLo0Gkfe3emgNjlALYIpAjxFuAAOB9gDzj1wTYbli9WAHFccGOaQHFP8ETpAYruAHWIAA).

**Comment by shreevatsa** [comment]
Good catches, thanks for noticing and reporting. We should fix…

**Comment by akprasad** [comment]
Thanks! Since these are typos as well, can you fold these into #35?

**Comment by vipranarayan14** [comment]
Sure! While doing that, would you want me to format the file using [Prettier](https://prettier.io/)? I noticed some inconsistencies in the style, viz. closing of the meta tags, indentation and splitting of multi-line tags, etc.

**Comment by akprasad** [comment]
Formatting seems a little larger, so let's do that in a separate PR -- thanks!

**Comment by vipranarayan14** [comment]
Fixed in #35.
