### ISSUE TITLE
[prakriya] Add support for समुह्यात्

### ISSUE THREAD

**Issue by akprasad** [ambuda-org/vidyut#40]
Implement https://ashtadhyayi.com/sutraani/7-4-23 in the `angasya` module to support this form.

**Comment by akprasad** [comment]
@yashkhasbage25 I think this would be a nice place to start.

**Comment by yashkhasbage25** [comment]
एतत् पश्यतु महोदय।
https://github.com/ambuda-org/vidyut/blob/c42db387669185cb30fd79b2ebe21b6b0423d19b/vidyut-prakriya/src/angasya.rs#L463

**Comment by akprasad** [comment]
क्षमस्व यन् मया विस्मरता पूर्वम् एव कृतम्। अन्यत् तावत् क्रियतां भवता -- 

https://ashtadhyayi.com/sutraani/6/1/137

इह `op_optional` इति प्रयुञ्जीत। `ac_sandhi.rs` इत्यस्मिन् लिखेत सूत्रम् . अपरस्मिन् काले, युकतरे स्थाने स्थापयेव।

**Comment by akprasad** [comment]
@yashkhasbage25 , +cc @vipranarayan14 

कानिचन नवीनानि test files इति स्थापितानि अत्र -- https://github.com/ambuda-org/vidyut/tree/main/vidyut-prakriya/tests, [इदं](https://github.com/ambuda-org/vidyut/blob/main/vidyut-prakriya/tests/pada_1_3.rs) च उदाहरणं तेषाम्।  यदि रोचते ते, किंचन पाणिनीयसूत्रं स्वीकृत्य test case इति रचयेत् । इदनीम् pada_7_4 इति रचयामि ...

**Comment by akprasad** [comment]
^ @shreevatsa  @skmnktl @vbasky as well if you have interest -- an easy way to contribute is to pick a sutra, find examples and counterexamples in the kashika vrtti, and create a test like the ones you see here.

**Comment by yashkhasbage25** [comment]
Thanks @akprasad for helping with this. 
It was taking too long for me. Rather I will help with tests for now.
