### ISSUE TITLE
[prakriya] ढत्व in ध्वम् and षीध्वम् is not possible if the anga is not ending with इण्

### ISSUE THREAD

**Issue by vipranarayan14** [ambuda-org/vidyut#45]
Due to the sutra विभाषेटः [8.3.79](https://ashtadhyayi.com/sutraani/8/3/79), the ध् in ध्वम् (लिट/लुङ्) and षीध्वम् (आशीर्लिङ्) is optionally replaced by ढ्, if the anga ends with इण् and is followed by इट् (aagama).

If the anga does not end with इण्, then the sutra cannot apply.

But I noticed that vidyut applies this sutra for many dhatus whose anga is not इण्-अन्त। Some of the examples are:

- [स्पर्धँ](https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0003):  **पस्पर्धिढ्वे** , पस्पर्धिध्वे / **स्पर्धिषीढ्वम्** , स्पर्धिषीध्वम् / **अस्पर्धिढ्वम्** , अस्पर्धिध्वम्
- [राजृँ](https://ambuda-org.github.io/vidyullekha/?dhatu=01.0956&tab=tin):  **रेजिढ्वे** , रेजिध्वे , **रराजिढ्वे** , रराजिध्वे / **राजिषीढ्वम्** , राजिषीध्वम् / **अराजिढ्वम्** , अराजिध्वम्
- [भाषँ](https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0696):  **बभाषिढ्वे** , बभाषिध्वे / **भाषिषीढ्वम्** , भाषिषीध्वम् / **अभाषिढ्वम्** , अभाषिध्वम्
 
AFAIK this is not correct. Please correct me if I am wrong.

**Comment by akprasad** [comment]
Thank you very much for filing this issue. Yes, I think this is a mistake -- I had interpreted 8.3.79 as इण्-भूतात् इटः as opposed to इण्-पूर्वकात् इटः . The Kashika clarifies इणः इत्येव, आसिषीध्वम् . I'll prepare a fix.

**Comment by akprasad** [comment]
I have a fix ready in #47. Do you know what the correct behavior is for बभूविध्वे? That is, is बभूविढ्वे also permitted?

**Comment by akprasad** [comment]
Merged #47 with tests -- I think this is fixed, but please file another issue if you see problems. I'll re-deploy now.
