### ISSUE TITLE
[prakriya] Form इयष्ठ of यजँ (01.1157) dhatu is not generated

### ISSUE THREAD

**Issue by vipranarayan14** [ambuda-org/vidyut#46]
यजँ (01.1157) dhatu has two forms in lit lakara parasmaipadi: इयजिथ and इयष्ठ.  Refer [Siddhanta Kaumudi](https://ashtadhyayi.com/sutraani/6/1/15#hl=%E0%A4%87%E0%A4%AF%E0%A4%B7%E0%A5%8D%E0%A4%A0&section=kaumudi) and [Madhaviya Dhatu Vritti](http://scl.samsaadhanii.in/scl/dhaatupaatha/files/mA652.html).

But इयष्ठ is [not generated](https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.1157).

**Comment by akprasad** [comment]
Thank you for filing this issue. Do you know which rule prevents इडागम for इयष्ठ?

**Comment by akprasad** [comment]
I see we have 7.2.63 implemented already -- the implementation is just buggy.

I have a fix ready, but I notice that the system now generates विव्याढ:

sutra | text | result
-- | -- | --
७.४.६० | हलादिः शेषः | वि + व्यध् + थ
८.२.४० | झषस्तथोर्धोऽधः | वि + व्यध् + ध
८.३.७८ | इणः षीध्वंलुङ्लिटां धोऽङ्गात् | वि + व्यध् + ढ
८.४.४१ | ष्टुना ष्टुः | वि + व्यढ् + ढ
८.३.१३ | ढो ढे लोपः | वि + व्य + ढ
६.३.१११ | ढ्रलोपे पूर्वस्य दीर्घोऽणः | वि + व्या + ढ

Do you know how this should be prevented?

**Comment by akprasad** [comment]
Added to #47 . Would love if you could take a second look

**Comment by vipranarayan14** [comment]
Thanks for fixing it. I will take a look.

**Comment by vipranarayan14** [comment]
> Do you know which rule prevents इडागम for इयष्ठ? Is it [7.2.62](https://ashtadhyayi.com/sutraani/7/2/62) + [7.2.63](https://ashtadhyayi.com/sutraani/7/2/63)?

Yes. Due to [भारद्वाजनियम](https://ashtadhyayi.com/sutraani/7/2/63) the इडागम is optional. So, when there is इडागम, we have इयजिथ. When there is no इडागम, we have: यज् + थ --> यष् + थ ([8/2/36](https://ashtadhyayi.com/sutraani/8/2/36)) --> यष् + ठ ([8/4/41](https://ashtadhyayi.com/sutraani/8/4/41)) --> इयष्ठ (अभ्यासकार्य).

Reference: 
> अयमत्र संग्रहः ॥ अजन्तोऽकारवान्वा यस्तास्यनिट् थलि वेडयम् । ऋदन्त ईदृङ् नित्यानिट् क्राद्यन्यो लिटि सेड् भवेत् ॥ १ ॥ -- Siddhanta Kaumudi

> क्रादिनियमादिट् थलि भारद्वाजनियमादिड्विकल्पः इडभावे झल्परत्वात् "व्रश्च'' इत्यादिना षत्वम् -- Madhaviya Dhatu Vritti

Hope I answered your question.

**Comment by akprasad** [comment]
Thanks!

Merged #47 with tests -- I think this is fixed, but please file another issue if you see problems. I'll re-deploy now.
