### ISSUE TITLE
[installation] `aoeu` command not found in `create_all_data.sh`

### ISSUE THREAD

**Issue by ma08** [ambuda-org/vidyut#48]
When I tried to run the `make create_all_data` the following error occurs at [this line](https://github.com/ambuda-org/vidyut/blob/c853bfd4009a545e7579160e3666c1775fd32518/scripts/create_all_data.sh#L22) in the `create_all_data.sh` script.

![image](https://user-images.githubusercontent.com/7117039/218285519-34a105f2-342a-4f89-a9c8-7797d24e56a9.png)

I am assuming that it's a stray line as far as I could debug given that I was able to run the script successfully (I think) after removing `aoeu` line.

**Comment by akprasad** [comment]
Thanks! Fixed as part of `eddada3`.
