### ISSUE TITLE
Support a `classify_all` method

### ISSUE THREAD

**Issue by akprasad** [ambuda-org/vidyut#96]
### Problem

`Chandas` contains a `classify` method that returns a single result. But sometimes it is interesting to look at *all* possible results and let the user decide how to use them.

### Proposed solution

Create a `classify_all` method that returns all padyas (vrttas + jatis) that don't have a `None` match.

**Comment by MSSRPRAD** [comment]
How about changing the `classify` method entirely into a `classify_vrtta` method that returns a single result (which now also has a quality parameter).  We can have an analogous `classify_jati`  method for Jati metres (#98).

```
pub fn classify_vrtta(&self, text: impl AsRef<str>) -> MatchResult {}
pub fn classify_jati(&self, text: impl AsRef<str>) -> MatchResult {}
```

`classify_all` can then just return the best n results of Partial Matches by updating them in some data structure while iterating:

```
pub fn classify_all(&self, text: impl AsRef<str>, best_n: usize) -> Vec<MatchResult> {}
pub struct MatchResult {
    matched: Option<Matched>,
    match_type: Vec<MatchType>,
    aksharas: Vec<Vec<Akshara>>,
}

pub enum Matched {
    Vrtta(Vrtta),
    Jati(Jati),
}

pub enum MatchType {
    Partial(usize), // Representing Quality of match
    Prefix,
    Pada,
    Full,
}
```
@akprasad

**Comment by MSSRPRAD** [comment]
> Having both `classify_vrtta` and `classify_jati` feels too complex -- an end user won't necessarily know whether the meter is a vrtta or jAti, and we should make their life easier with a simple `classify` endpoint so that they don't have to make two calls.

Can't `classify_all` to be that endpoint? `best_n` can be defaulted to 1 (and first the Jati match is checked before vrtta match)?
 
> `best_n` is a nice idea but puts us in the position of having to decide what "best" means, but this seems dependent on the use case. `classify_all` without `best_n` is less sophisticated, but the return data is also more obvious and deterministic.

I felt when the database consists of several hundreds of schemes, it would be apt to ask for the best 5 or so than a match against every single scheme in the data.

**Comment by MSSRPRAD** [comment]
> pub fn classify(&self, text: impl AsRef<str>) -> Matches {
>   self.classify_all(text.as_ref(), 1)
> }

What kind of response struct should be returned? If classify is just returning one response, should it be the one giving Pada match / Prefix Match / None(edit_distance or any other metric) in case there is not Full match?
